package org.example.lab1.mybatis.model;

public class Grupe {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GRUPE.ID
     *
     * @mbg.generated Mon Mar 03 03:39:54 EET 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GRUPE.NUMERIS
     *
     * @mbg.generated Mon Mar 03 03:39:54 EET 2025
     */
    private Integer numeris;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GRUPE.ID
     *
     * @return the value of PUBLIC.GRUPE.ID
     *
     * @mbg.generated Mon Mar 03 03:39:54 EET 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GRUPE.ID
     *
     * @param id the value for PUBLIC.GRUPE.ID
     *
     * @mbg.generated Mon Mar 03 03:39:54 EET 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GRUPE.NUMERIS
     *
     * @return the value of PUBLIC.GRUPE.NUMERIS
     *
     * @mbg.generated Mon Mar 03 03:39:54 EET 2025
     */
    public Integer getNumeris() {
        return numeris;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GRUPE.NUMERIS
     *
     * @param numeris the value for PUBLIC.GRUPE.NUMERIS
     *
     * @mbg.generated Mon Mar 03 03:39:54 EET 2025
     */
    public void setNumeris(Integer numeris) {
        this.numeris = numeris;
    }
}