package org.example.lab1.mybatis.dao;

import java.util.List;
import org.example.lab1.mybatis.model.Pasirenkamasisdalykas;
import org.mybatis.cdi.Mapper;

import javax.persistence.ManyToOne;

@Mapper
public interface PasirenkamasisdalykasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PASIRENKAMASISDALYKAS
     *
     * @mbg.generated Mon Mar 03 03:39:54 EET 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PASIRENKAMASISDALYKAS
     *
     * @mbg.generated Mon Mar 03 03:39:54 EET 2025
     */
    int insert(Pasirenkamasisdalykas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PASIRENKAMASISDALYKAS
     *
     * @mbg.generated Mon Mar 03 03:39:54 EET 2025
     */
    Pasirenkamasisdalykas selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PASIRENKAMASISDALYKAS
     *
     * @mbg.generated Mon Mar 03 03:39:54 EET 2025
     */
    List<Pasirenkamasisdalykas> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PASIRENKAMASISDALYKAS
     *
     * @mbg.generated Mon Mar 03 03:39:54 EET 2025
     */
    int updateByPrimaryKey(Pasirenkamasisdalykas record);
}